from data_types import *
line1 = 'Wilson Sonsini Goodrich & Rosati'.replace(',','').replace('.','').upper()
line2 = '139 Townsend St, Suite 150'.replace(',','').replace('.','').upper()
line3a = 'San Francisco, CA 94404'.replace(',','').upper()
line3b = 'San Francisco, CA'.replace(',','').upper()
a = AddressParser(line1,line2,line3a)
b = AddressParser(line1,line2,line3b)
repairer = AddressRepairer()
repairer.add_good_address(a)
print 'address a: ' + str(a.make_address())
print 'address b: ' + str(b.make_address())
repairer.repair_address(b)
print 'repaired address b: ' + str(b.make_address())
print a.make_address() == b.make_address()
